### ISSUE TITLE
Error message is hard to read.

### ISSUE THREAD

**Issue by munyagu** [danieltj27/Dark-Mode#10]
![error_msg](https://user-images.githubusercontent.com/19759754/31812088-d401cbf8-b5bc-11e7-9b00-63e55c576783.jpg)

**Comment by danieltj27** [comment]
Oops, thanks for raising an issue!

**Comment by danieltj27** [comment]
I ran into some complications with this because changing the `color` on the body also changed some of the colours in the admin toolbar as well. Will come back to this one.

**Comment by danieltj27** [comment]
Thanks again for the report, fixed in 3190a83.
