### ISSUE TITLE
Plugin Editor Warning isn't dark

### ISSUE THREAD

**Issue by pento** [danieltj27/Dark-Mode#106]
To reproduce:

- Have a fresh install of WordPress, or at least one that you've never visited the plugin editor on.
- Visit the plugin editor.

<img width="633" alt="plugin editor warning" src="https://user-images.githubusercontent.com/352291/42124948-20d24f2e-7cb0-11e8-9312-66589aca540f.png">

**Comment by danieltj27** [comment]
Fixed in commit ecf6439.
