### ISSUE TITLE
Fallback Media Uploader button is incorrectly styled

### ISSUE THREAD

**Issue by pento** [danieltj27/Dark-Mode#110]
To reproduce:

- Go to Media -> Add New.
- Switch to the browser uploader.

The "Choose file" button is very hard to read.

**Comment by danieltj27** [comment]
After looking into this, I don't think this is something that can be fixed without WordPress core doing something to remedy it first. It would mean making a custom button just for Dark Mode to then style it correctly which I don't think is a good approach by having a different UI button between 'normal' and Dark Mode.

Refer to [this StackOverflow answer](https://stackoverflow.com/a/714626/7236046) for some extra details on the issue. I'll mark this one as won't fix for now unless anything changes to allow this to be changed with pure CSS.

**Comment by pento** [comment]
This would need to be fixed before merge, so I'd advise doing it now, rather than later. It's okay to hack it in a bit: output new HTML on the `pre-html-upload-ui` action, and add some CSS to hide the old HTML.

**Comment by danieltj27** [comment]
I'll take a look then, perhaps someone in #design on Slack can create a design for it as it's a new bit of UI that Core should adopt for consistency too.

**Comment by danieltj27** [comment]
See this for reference: https://wordpress.slack.com/archives/C02S78ZAL/p1530515468000270

**Comment by hedgefield** [comment]
@pento What do you find hard to read about it? Using Chrome on Mac the button is white with black text, so the contrast ratio is great. It is a bit harsh, such a bright button in a dark environment, and it could do with more height. Do you have any other problems with it? Does it look very different on other OS/browsers?

**Comment by danieltj27** [comment]
Just quickly weighing in here, on macOS High Sierra, the button is white with black text so I couldn't replicate the contrast issue. It could do with an upgrade though as the browser default file uploads aren't particularly nice to look at. Open to suggestions nonetheless.

**Comment by pento** [comment]
Ugh, nevermind: this is a bug in Chrome on MacOS Mojave, Safari looks fine.

**Comment by hedgefield** [comment]
Ahh interesting. Mojave has its own Dark Mode, doesn't it?

**Comment by pento** [comment]
Yeah, it's exposed to apps, some existing UI is automatically converted (eg, menus), other parts are converted when the app is recompiled against the new libs (eg, preferences panels, popups). More complex apps need to implement their own support for it.

**Comment by danieltj27** [comment]
I think if we're changing the file upload appearance, it'd be nice to have some consistency, although I don't know if we need to take this forward re @pento [reply](https://github.com/danieltj27/Dark-Mode/issues/110#issuecomment-401706118).

**Comment by pento** [comment]
Don't need to make any changes, this was a Mojave bug, not a Dark Mode bug.
