### ISSUE TITLE
OS Dark Mode support

### ISSUE THREAD

**Issue by pento** [danieltj27/Dark-Mode#112]
With MacOS adding a Dark Mode, and Windows having had a Dark Mode since forever, it would be good to obey the OS dark mode settings.

Windows exposes this through [-ms-high-contrast](https://msdn.microsoft.com/en-us/library/hh771830(v=vs.85).aspx), and the [w3c is discussing adding a standard media query](https://github.com/w3c/csswg-drafts/issues/2735) for dark mode. I think it would be valuable to hold off on any core merge until the w3c sorts out their plans.

**Comment by danieltj27** [comment]
I like the idea, but this presents two issues;

1. If a Dark Mode preference is sent, do we honour the user setting that is saved or ignore it in favour of the browser preference that is sent across in the request.

2. Should we really wait for the W3c to _potentially_ implement this and wait for all major/supported browsers to play catch up and add it in? This point alone would delay a merge for many years.

I don't think we should hold off on a merge for this.

**Comment by pento** [comment]
1. The user preference could be one of three options: "Never use dark mode", "System default", and "Always use dark mode".

2. MacOS Mojave is due for release in a few months, I'd be inclined to see if the w3c makes a decision by then, or if the browsers decide to push ahead with their own standard: assuming Chrome and Safari are pretty quick to add such a flag (even if it's browser-specific flag, PostCSS's Autoprefixer will quickly add support for it). I don't mind us adding a feature that only works in the latest browsers, as long as there's a clean fallback for everyone else.

**Comment by danieltj27** [comment]
We'll have to wait and see what (if anything) gets implemented first before we can build something to support it. From the issue link above, it's still very much in discussion phase.

**Comment by danieltj27** [comment]
I'm in favour of this, but I'm closing it until there is a proper working implementation that can be followed. It could take a number of years for it to be properly adopted.

**Comment by pento** [comment]
Given that Mojave is only a few months away, I think it's reasonable to wait and see if the pressure from that will cause w3c/browsers to move faster.

**Comment by danieltj27** [comment]
That's fine, we can reopen the issue in due course if need be.
