### ISSUE TITLE
Add class to dashboard body

### ISSUE THREAD

**Issue by danieltj27** [danieltj27/Dark-Mode#113]
It's just occurred to me that when Dark Mode is enabled, there isn't a CSS class applied to the body tag. This would make it easier to style elements on the page for plugins rather than including extra stylesheets.

**Comment by danieltj27** [comment]
I'm not sure if this should be added or not as technically we're suppose to be in a feature freeze type of state here and arguably, plugins do have access to the user preference through `get_option()`. I think it might be worth coming back to this at a later date if needed.

**Comment by pento** [comment]
Yes, there should be a class on the body.

Also, I wouldn't get too hung up about feature freeze, when a change like this would need to be made for a merge proposal to be accepted.

**Comment by danieltj27** [comment]
Added this in commit 5195ca7.
