### ISSUE TITLE
Add more screenshots to plugin directory

### ISSUE THREAD

**Issue by danieltj27** [danieltj27/Dark-Mode#115]
A [support topic](https://wordpress.org/support/topic/more-screen-shots/) from WordPress.org was posted:

> Please provide more screen-shots. E.g. Plugin page, page/post editor, settings etc.
> 
> The current screen-shots effectively demonstrate the colour scheme variation but it would be better to additionally see the end result of the plugin more completely without having to install it.

There probably should be an extra one or two to demonstrate key areas within the dashboard.

**Comment by danieltj27** [comment]
I've updated a couple of images during the 3.1 release.

**Comment by ClarusDignus** [comment]
The increased variety of screen-shots better depict the aesthetic. Appreciated. Thanks.
