### ISSUE TITLE
Support for Redux Framework

### ISSUE THREAD

**Issue by SkylarAstarot** [danieltj27/Dark-Mode#117]
The Wordpress theme Electro using **Redux Framework** v3.6.9 not support Dark Mode completly.
https://i.imgur.com/MByZ1h6.png

Add completly dark mode in this Framework.

**Comment by danieltj27** [comment]
Thanks for taking the time to log this, however third party tools/plugins will need to look at supporting Dark Mode in their own ways. It's not something that we'll be looking to add support for at this time.

Information on supporting Dark Mode can be found here: https://github.com/danieltj27/Dark-Mode/wiki/Help:-Plugin-Compatibility-Guide
