### ISSUE TITLE
Add dark-mode class to admin_body_class

### ISSUE THREAD

**Issue by elliotcondon** [danieltj27/Dark-Mode#118]
Hi @danieltj27 

Elliot here from [ACF](https://www.advancedcustomfields.com/).

I'm interested in supporting Dark Mode in the Advanced Custom Fields plugin, and wonder if you would consider hooking into the [admin_body_class](https://developer.wordpress.org/reference/hooks/admin_body_class/) filter and appending a 'dark-mode' class.

This would allow plugin developers (like me) to add Dark Mode styles without needing to enqueue a separate file. Instead, we could create rules within our existing CSS like this:
```
body.dark-mode .my-thing {

}
```

What do you think?

Thanks
Elliot

**Comment by danieltj27** [comment]
Hi Elliot, I added a filter to the body class in 3.1 ([source](https://github.com/danieltj27/Dark-Mode/blob/master/class-dark-mode.php#L245-L262)). It's not been released yet as I'm working towards supporting Gutenberg (which I'm sure you know is quite the task!) but will be out in the near (ish) future.

Hope that helps and thanks for supporting Dark Mode! 😄

**Comment by elliotcondon** [comment]
Hi @danieltj27 

Awesome, you're already on it!
Thanks mate, I'm happy to be supporting this 👍

**Comment by danieltj27** [comment]
😄 appreciate the kind words! I'll close this off.

I'm not sure when it'll be ready as it'll take a bit of work to get Gutenberg fully dark, but sometime soon I'm hoping (time permitting etc).

**Comment by danieltj27** [comment]
Retroactively added `FIXED` label. Sorry for any activity notifications!
