### ISSUE TITLE
Some tweaks to the Admin dashboard

### ISSUE THREAD

**Issue by hedgefield** [danieltj27/Dark-Mode#12]
v1.1 is a really good start! I'll keep this running on my development environment and offer some suggestions every now and then.

This one focuses on the WP admin dashboard, tweaking a few things to create some harmony.

<img width="1045" alt="colors" src="https://user-images.githubusercontent.com/6073772/31815700-bcc870e2-b58d-11e7-8527-15ab3ab90dc3.png">

- I reversed the color shade of the widget and the background. In general, it feels nicer to the eye when the thing with the most depth, the furthest away in the Z-axis, the bottom layer, is the darkest thing, and what's layered on top of it becomes gradually lighter. Doesn't mean you can't use a darker color here and there for specific elements :)

- I changed the body background color to `#23282d` to match the sidebar. It's up for debate as it effectively removes the 'shape' of the sidebar, blending it in with the background, but I think it looks nice, and it felt a little weird having a grey sidebar on a dark blue background.

- The biggest eyesore here were the dividers on the dashboard widgets. They stand out a lot, being `#eee`, so I changed them to match the background: `#283138`, and I removed the borders around the widgets themselves.

- I changed the widget color to `#32373c`, same as the foldout in the sidebar, to decrease the amount of colors used. In general I think we can take the default WP color theme and borrow values from there, most people will be using that one, and then we just have to make sure it also looks okay with the other color themes.

- I did a quick test to make the light grey secondary buttons a dark shade of blue. I haven't consulted the WP colors for this one, just tried a random value, but it could give you an idea of where to look. The button color is `#535063`, the border and box shadow `#283138`. It's AAA compliant.

The original, for reference:

<img width="1045" alt="oldcolors" src="https://user-images.githubusercontent.com/6073772/31815888-69870870-b58e-11e7-9170-cf888333ea62.png">

**Comment by danieltj27** [comment]
This is awesome, thanks for taking the time to go through all of this. The dividers and secondary buttons were an oversight on my part that'll need fixing up. I'm not sure when I'll get around to this so if anyone beats me to it, feel free to send a PR (please, hah).

**Comment by danieltj27** [comment]
Committed in e88e9de.

I took your suggestions on board and I've made some changes to refine the colours a bit better as well - plus fixed so of those bugs! 1.1.1 dropping soon.
