### ISSUE TITLE
There doesn't seem to be enough contrast on notices

### ISSUE THREAD

**Issue by cwpnolen** [danieltj27/Dark-Mode#120]
The background color of a notice is too close to the background color of the body. Updating this background will make notices stand out more. 

__Current Notice__
![dark-mode-current-notice](https://user-images.githubusercontent.com/2512650/44921986-0b930080-ad12-11e8-8db0-a61c0709e03a.png)

__Proposed Update__
Use the same background color that is used on `wp-submenu` class: `#32373c`
![dark-mode-proposed-notice](https://user-images.githubusercontent.com/2512650/44922097-662c5c80-ad12-11e8-9b7b-eec8fded37f4.png)

**Comment by danieltj27** [comment]
Thanks for flagging this. It'll get addressed in the next release.

**Comment by cwpnolen** [comment]
Thanks for making this project. I love using dark themes.

**Comment by danieltj27** [comment]
Fixed in commit 54cd06a.
