### ISSUE TITLE
Soms CSS updates and improvements

### ISSUE THREAD

**Issue by MPolleke** [danieltj27/Dark-Mode#121]
Hi,
There are some CSS rules missing in Dark Mode that are used inside the WP Dashboard.

In common.css there is a class for .alternate at line 664. It would need an update from this plugin, like:

```
.dark-mode .striped > tbody > :nth-child(odd),
.dark-mode ul.striped > :nth-child(odd),
.dark-mode .alternate {
    background-color: #23282d;
}
```
It can be used in dashboard widgets with an unordered list. The uneven list items and the even/alternate list items get a different background-color. Currently the alternate list item has a lightgrey background-color.
You can test it with this plugin at the dashboard:
https://wordpress.org/plugins/admin-users-logged-in/

Some more CSS that I miss, which can be tested with:
https://wordpress.org/plugins/chessgame-shizzle/ (About page)
It is used in widget headings on settingspages. The widget-top has a dark background and dark text. It needs a lighter text for contrast.

```
.dark-mode .widget .widget-top,
.dark-mode .menu-item-handle {
    color: #bbc8d4;
}
```

**Comment by MPolleke** [comment]
Alternate list-item without dark-mode CSS:
![alternate](https://user-images.githubusercontent.com/4286740/44982402-52c4ff80-af65-11e8-963a-ceffc6aac631.jpg)

Widget-top without dark-mode CSS, the text should be light:
![widget-top](https://user-images.githubusercontent.com/4286740/44982452-7b4cf980-af65-11e8-82e6-6b087b895254.jpg)

**Comment by danieltj27** [comment]
Thanks for reporting this.

I'll investigate this and see what we can do. I've not seen those screens before. Is it part of a plugin? If so, that's not something that this plugin will cover. Plugins will need their own Dark Mode styles.

I'll take a look and see what I can find though. 👍

**Comment by MPolleke** [comment]
Hi, the adaptations are for CSS that is in /wp-admin/css/common.css
Sorry for the confusion.

**Comment by danieltj27** [comment]
[See #151 for more info](https://github.com/danieltj27/Dark-Mode/issues/151).
