### ISSUE TITLE
Add PHPCS support for coding standards check

### ISSUE THREAD

**Issue by GaryJones** [danieltj27/Dark-Mode#122]
One of the feedback items mentioned in the feature proposal post comments was about the lack of coding standards checking. I'm happy to work on this.

First stage would be the get the `composer.json` and `.phpcs.xml.dist` setup, and a later stage would be to fix the violations it reports. Once fixed, this could then be tied into Travis to automatically check any new commits / PRs.

**Comment by danieltj27** [comment]
Hi @GaryJones, thanks for chipping in. I'm not familiar with PHPCS at all so if you could provide some guidance or even help get it set up I'd really appreciate it. Thanks! 😄
