### ISSUE TITLE
"Add New" pull-down displayed when Gutenberg activated is unstyled

### ISSUE THREAD

**Issue by mimosafa** [danieltj27/Dark-Mode#126]
In edit.php (e.g. All Posts), "Add New" link will be pull-down, when Gutenberg plugin is activated.
That element is not dark-mode styled.

**Comment by megane9988** [comment]
![image](https://user-images.githubusercontent.com/1205958/45546355-04164000-b858-11e8-8d88-efc403cac71b.png)

**Comment by danieltj27** [comment]
This is part of the UI that Gutenberg adds so will need to be addressed in [WordPress/Gutenberg](https://github.com/WordPress/gutenberg/).

**Comment by mimosafa** [comment]
@danieltj27 Understood, thank you
