### ISSUE TITLE
Add Dark Mode to Gravity Form

### ISSUE THREAD

**Issue by vitalclick** [danieltj27/Dark-Mode#132]

**Comment by vitalclick** [comment]
The gravity form does not show on gravity form page by deafult in the backend. I'm trying to use the following hook to add it to Gravity Form: 

`add_action( 'doing_dark_mode', 'my_plugin_dark_mode', 10, 1 );
function my_plugin_dark_mode( $user_id ) {
	wp_enqueue_style( 'my_plugin_dark_mode', 'path/to/css/dark-mode.css' );
}`

Can you help me here to get the hook to load it on Gravity Form Page

**Comment by danieltj27** [comment]
Hi there, do you mean on the Gravity Form page within the dashboard or on the front-end of the website?

The code you've posted above will enqueue a stylesheet whilst Dark Mode is activated anywhere within the dashboard, not just specifically on the Gravity Form page.

If you're wanting to style the Gravity Form page in the dashboard, I think it might be best to get in touch with the Gravity Forms developer directly and see if they'll support Dark Mode.

**Comment by vitalclick** [comment]
I meant the Gravity Form page within the dashboard. It works everywhere except within the Gravity Form page within the dashboard.

**Comment by danieltj27** [comment]
Oh okay, in that case you'll need to speak to the developers of Gravity Forms and see if they'll consider supporting Dark Mode. I don't have a copy of Gravity Forms so I can't test anything unfortunately.
