### ISSUE TITLE
Dark background is applied to Gutenberg editor in WordPress 5.0

### ISSUE THREAD

**Issue by ZebulanStanphill** [danieltj27/Dark-Mode#133]
After updating my site to WordPress 5.0, Gutenberg began to have dark mode styles applied to it. This was not the case with WordPress 4.9.8 and the Gutenberg plugin version 4.6.1. Here is a picture of what this looks like in Twenty Nineteen:
![image](https://user-images.githubusercontent.com/19592990/49606135-24860000-f958-11e8-8e3d-a5a1900a9c4e.png)

I'm guessing this is not intentional.

Tested on WordPress 5.0 with Dark Mode plugin 3.1 and Twenty Nineteen theme 1.0.

**Comment by KhakiMan** [comment]
Seeing the same problem. Makes adding pages unusable.

**Comment by danieltj27** [comment]
[See #151 for more info](https://github.com/danieltj27/Dark-Mode/issues/151).
