### ISSUE TITLE
CSS variables instead of SCSS variables

### ISSUE THREAD

**Issue by JoryHogeveen** [danieltj27/Dark-Mode#141]
Might be a nice feature to add compatibility with CSS variables.
This would allow other plugins and theme developers to use these variables to make their code easily compatible with dark mode.

More info: https://www.w3schools.com/css/css3_variables.asp

**Comment by danieltj27** [comment]
[See #151 for more info](https://github.com/danieltj27/Dark-Mode/issues/151).
