### ISSUE TITLE
Filter `not_using_dark_mode` is redundant

### ISSUE THREAD

**Issue by JoryHogeveen** [danieltj27/Dark-Mode#145]
I'd say keep it simple and just allow `is_using_dark_mode` as a filter. `not_using_dark_mode` seems a bit redundant to me.

**Comment by danieltj27** [comment]
I disagree, I think there may be edge cases where it might be useful to filter any output from the function just in case. Plus backwards compat etc.

**Comment by JoryHogeveen** [comment]
I can't think of any use case since a single filter is more than sufficient for this.
Backwards compatibility is easily done if you want that.
