### ISSUE TITLE
Request for help: Toolbar "enabler" via Ajax?

### ISSUE THREAD

**Issue by deckerweb** [danieltj27/Dark-Mode#150]
Hi there!
In general, I really love this plugin, and use it very often. It is very good and I would love to see this in Core, finally! ;-)

Well, I have a request for help:
I would love to integrate your plugin with my own Toolbar Extras plugin and add a enable/disable action to the Toolbar, that triggers a Ajax (or even JS?) action to enable or disable the Dark Mode.

However, I have never worked with Ajax and really don't know where to start or how to implement this.

Any help or pointing in the right direction would be awesome!
Thanks in advance!! :)

**Comment by danieltj27** [comment]
Hi, you should take a [look this for help](https://codex.wordpress.org/AJAX_in_Plugins) with getting Ajax working plugins. It should give you a good starting point to work with. Thanks 👍

**Comment by deckerweb** [comment]
Thanks for the heads up!

However, this won't help as it is too general, I need more help for the exact issue I have. Toolbar is not a settings page whatsoever. It's all different. Don't know how to go forward, but I will keep digging.
