### ISSUE TITLE
Title is not readable

### ISSUE THREAD

**Issue by munyagu** [danieltj27/Dark-Mode#18]
Title's color is #fff and input field's background-color is #fff.

![post_title](https://user-images.githubusercontent.com/19759754/31884814-5b0806b2-b829-11e7-8607-af3e61c69766.png)

**Comment by danieltj27** [comment]
Thanks, the background for the post title should be the dark grey like the other form elements. Obviously some sort of specificity battle going on between the elements.

**Comment by danieltj27** [comment]
Fixed in commit 877a533.
