### ISSUE TITLE
Add .updates-table style

### ISSUE THREAD

**Issue by megane9988** [danieltj27/Dark-Mode#19]
WordPress Updates page's style is not applied.

![http://megane-blog.com/wp-content/uploads/2017/10/7801bcbb2be576a3a3365326a37d50ba.png](http://megane-blog.com/wp-content/uploads/2017/10/7801bcbb2be576a3a3365326a37d50ba.png)

**Comment by danieltj27** [comment]
Fixed in PR #20.
