### ISSUE TITLE
Implement as an Admin Color Scheme

### ISSUE THREAD

**Issue by Viper007Bond** [danieltj27/Dark-Mode#2]
Rather than adding a new checkbox to the profile page, I _think_ this could be implemented simply as a new Admin Color Scheme using [`wp_admin_css_color()`](https://developer.wordpress.org/reference/functions/wp_admin_css_color/). Then people just pick it as a theme.

**Comment by danieltj27** [comment]
Thanks for the suggestion - the idea was that the user would still be able to have an admin colour scheme active, but also be able to darken the overall lighter colours in the dashboard UI. I'll this open to discuss though. Worth exploring.

**Comment by hedgefield** [comment]
Yeah it might be an idea worth investigation. Making a dark mode work with all the available color schemes (visually and accessibility-wise) might be more work than just offering one definitive dark color scheme. Though I can appreciate the effort to make it as accommodating as possible 👍

**Comment by danieltj27** [comment]
I think it's time to close this now.

This has been discussed on the Making WordPress Slack in #design and #accessaibility channels but in case anyone missed those chats, the overall conclusion is the following:

1. Admin colour schemes change the dashboard menu and toolbar to a variety of six different styles, Dark Mode does not (and should not) style these areas.

2. A user may wish to have Dark Mode on and a colour scheme active at the same time (for example, Sunrise, the red colour scheme and Dark Mode together).

3. Dark Mode is specifically for changing the admin dashboard UI (such as tables, form controls etc) and not for anything else so it falls outside the remit of a colour scheme.

If anyone has anything to add to this then feel free to do so, I'll leave this issue unlocked for further discuss but consider it closed/done.
