### ISSUE TITLE
.notice-warning.notice-alt are hard to read.

### ISSUE THREAD

**Issue by megane9988** [danieltj27/Dark-Mode#23]
.notice-warning.notice-alt are hard to read.
If you have already decided, please apply that style.

![http://megane-blog.com/wp-content/uploads/2017/10/f08109aa3964c9b12dea94efff0b7209.png](http://megane-blog.com/wp-content/uploads/2017/10/f08109aa3964c9b12dea94efff0b7209.png)

![http://megane-blog.com/wp-content/uploads/2017/10/ecb3d042060f09b89a0feb453b271826.png](http://megane-blog.com/wp-content/uploads/2017/10/ecb3d042060f09b89a0feb453b271826.png)

**Comment by danieltj27** [comment]
This will be fixed in a future commit. Thanks for picking up on it though.
