### ISSUE TITLE
Add Plugin Page needs formatted

### ISSUE THREAD

**Issue by DustinHartzler** [danieltj27/Dark-Mode#26]
Leaving this here as this page needs to be styled:
http://xxxxxx.dev/wp-admin/plugin-install.php

<img width="1259" alt="dark mode plugins" src="https://user-images.githubusercontent.com/2293077/32175313-ede48cfe-bd5a-11e7-97b6-ab7326638e1c.png">

**Comment by danieltj27** [comment]
This has been fixed in my local build, thanks for picking this up though! :)
