### ISSUE TITLE
More unstyled areas in plugins modal and comments table

### ISSUE THREAD

**Issue by danieltj27** [danieltj27/Dark-Mode#28]
There are a few more areas that are still not styled properly.

- The comments table has a few links which aren't styled correctly.
- The plugin modal isn't styled (click a plugins 'View Details' link).
- The customiser really needs styling at this point at it doesn't match.
- The TInyMCE editor needs styling too I think (although works okay at the moment).

Overall everything could be with a slight refinement and the overall button UIs need tweaking, the blue colour seems off really. Might need to use some non-standard colour palette colours to make it look nicer.

**Comment by Presskopp** [comment]
I changed the blue from 6dbfff to 00A0D2 (taken from wordpress.org feature icons) and I like it..

**Comment by danieltj27** [comment]
Updated the blue colour in commit d791ba9 as well as styled some areas in the comment section. At the moment my current feelings are to leave the TinyMCE editor as that's controlled by themes (well, it can be) and to just style the other bits on the list instead. Probably the best way forward.

**Comment by ihorvorotnov** [comment]
You can check if the active theme supports custom editor styles with `current_theme_supports( 'editor-style' )` and apply dark mode if not. Just a $0.05 idea.

**Comment by danieltj27** [comment]
I've made further changes in commit a4d7179 but I'll keep this open because there's still some more bits and pieces to address.

Thanks @ihorvorotnov, I think the best course of action is the leave the editor as it is because it can be swapped out for another editor if someone wants to, plus themes can change the editor styles too with the editor styles support tag you mentioned above so I think it's best to leave TinyMCE along for now.

**Comment by Presskopp** [comment]
I may be wrong, but I think we need to add #wpwrap like in:
`body table, #wpwrap {
    background-color: #191f25;
    border-color: #32373c
}`

**Comment by danieltj27** [comment]
@Presskopp what does `#wpwrap` do? Where is that used?

**Comment by danieltj27** [comment]
I've done some more updates to the customiser UI in commit e263688.

Still has some way to go; some extra little bits still need styling but mostly there.

**Comment by danieltj27** [comment]
Closing this issue and opening another to focus on the customiser specifically as this was originally opened for just the plugins & comments tables.

**Comment by Presskopp** [comment]
to set a color for #wpwrap avoids breakage,see screenshot..

**Comment by Presskopp** [comment]
![wrap](https://user-images.githubusercontent.com/18373563/32997680-6d84cda0-cd93-11e7-9d6b-6f8d36526802.png)

**Comment by danieltj27** [comment]
Ahh I see, I’ll look into this.
