### ISSUE TITLE
Feedback link in admin toolbar

### ISSUE THREAD

**Issue by danieltj27** [danieltj27/Dark-Mode#29]
I'd like to include a feedback link to issues here on GitHub or maybe to the plugins support page on WordPress.org so we can gather more feedback from people using the plugin.

I think it'd also be important though to be able to turn off the toolbar link using a flag that can be defined in wp-config.php in case people don't want to see it.

Thoughts? PRs?

**Comment by Presskopp** [comment]
Would it be feasible to add 1 or 2 links to the plugin description on wp-admin/plugins.php ?

**Comment by danieltj27** [comment]
Yeah, a link to add feedback from that area would be fine. I thought that it'd be nice to include a link to provide feedback in the toolbar only when Dark Mode is on. That way it's easily visible and only when users are actually using the Dark Mode colours.

Will be worth exploring with a few options though anyway to see how it all works out.

**Comment by danieltj27** [comment]
Added feedback link in commit d791ba9.
