### ISSUE TITLE
Style the customiser user interface

### ISSUE THREAD

**Issue by danieltj27** [danieltj27/Dark-Mode#34]
The customiser needs to be styled still, whilst most of it is there, it's still missing some bits and pieces and could do with another update to finish off some extra elements.

This was originally discussed in #28 but has since been closed as it's a bit off-topic for this. Marking this as `Good First Issue` for anyone new to the project wanting to get involved.

**Comment by danieltj27** [comment]
#15 is related to this. I'm not sure why that got closed.

**Comment by Presskopp** [comment]
What's the goal (optically)?

I used

`.wp-full-overlay-sidebar, div.description.customize-section-description.open {
    background-color: #191f25 !important;
}`

while testing

 but I don't like the !important (needed only for description class - well, as this will be a plugin, maybe it's ok)

And is this enough 'darkness'? What about the color of texts?

![image](https://user-images.githubusercontent.com/18373563/33535453-e2b5a05c-d8ad-11e7-982c-15dbd83548d4.png)

**Comment by danieltj27** [comment]
The customiser should now be mostly styled. Anything that isn't was missed accidentally and should have a new bug opened against it.

Fixed in commit 0afc3b9.
