### ISSUE TITLE
Automatic Dark Mode doesn't work as expected

### ISSUE THREAD

**Issue by danieltj27** [danieltj27/Dark-Mode#35]
When setting Dark Mode to automatic between two time frames, it doesn't seem to work as expected and often comes online at random times which isn't good.

This SO question seems to be something to consider as it's along the right lines but doesn't have an effective implementation for this case scenario.

Link: https://stackoverflow.com/q/24740786/7236046

**Comment by Presskopp** [comment]
https://github.com/danieltj27/Dark-Mode/pull/40

**Comment by danieltj27** [comment]
Fixed in #40 - pull merged into master.
