### ISSUE TITLE
Style the plugin editor page

### ISSUE THREAD

**Issue by radfordwill** [danieltj27/Dark-Mode#37]
The plugin editor should be styled also I think. Codemirror already has several dark themes available. 
https://codemirror.net/theme/

I use one-dark a lot.
https://github.com/Aerobird98/codemirror-one-dark-theme

What do you think?

**Comment by danieltj27** [comment]
Thanks for stopping by. I'll take a look and see what can be done. I'm not opposed to styling the code editor, although I'm against styling the TinyMCE editor (for posts etc). If you get to it before me, submit a PR for it be reviewed. Do you know if there are any hooks for the code editor?

**Comment by radfordwill** [comment]
Style the plugin editor page

No I couldn't find any specific hooks.
I tried to use codemirror's settings api to modify the settings after it is loaded..

https://codemirror.net/doc/manual.html#api_configuration

`
jQuery(document).ready(function () {
	var codeEditor = CodeMirror.fromTextArea(codeEditor, {
		cm.setOption(option: theme, value: 'one-dark')
	});
});
`

In the end I loaded the theme's style normally in a plugin and used a modified version of the style sheet.

I had to hack one and replace the sheet's main class since I could not find a hook. Hacky. I only load it on the plugin and widget editor page for now so it does not conflict.
`
/*
    Name:       one-dark
    Author:     Török Ádám (http://github.com/Aerobird98)
    Original Atom One Dark Theme (https://github.com/atom/one-dark-syntax & https://github.com/atom/one-dark-ui)
*/


/* UI Theme /----------------------------------------------------------------------------------- */


.CodeMirror, .CodeMirror-scroll {
  font-family: 'Inconsolata, Monaco, Consolas, 'Courier New', Courier';
  font-weight: 300;
  font-size: inherit;
  background-color: #23282d;
  color: hsl(220, 14%, 71%);
}
div.CodeMirror-selected {
  background: rgba(204, 217, 255,0.05);
}
.CodeMirror-focused div.CodeMirror-selected {
  background: rgba(204, 217, 255,0.09);
}
.CodeMirror-lines {
  padding: 4px 0; /* Vertical padding around content */
}
.CodeMirror pre {
  padding: 0 4px; /* Horizontal padding of content */
}

/* Gutter & Folding */

.CodeMirror .CodeMirror-gutters, .CodeMirror-gutter {
  white-space: nowrap;
  border: none;
  background-color: #23282d !important;
}
.CodeMirror-linenumber {
  padding: 0 30px 0 30px;
  min-width: 20px;
  text-align: right;
  white-space: nowrap;
  color: hsl(220, 10%, 25%);
}
/* ...folding addon: fold/...  */
.CodeMirror-foldmarker {
  line-height: .3;
  cursor: pointer;
  color: hsl(220, 14%, 71%);
  background: rgba(204, 217, 255,0.05);
}
.CodeMirror-foldgutter {
  width: 15px;
  border: none;
}
.CodeMirror-foldgutter-open, .CodeMirror-foldgutter-folded {
  cursor: pointer;
}
.CodeMirror-foldgutter-open:after {
  content: "\25BE";
  color: hsl(220, 10%, 25%);
}
.CodeMirror.over-gutter, .CodeMirror-activeline .CodeMirror-foldgutter-open:after {
  color: hsl(220, 10%, 40%);
}
.CodeMirror-foldgutter-folded:after {
  content: "\25B8";
  color: hsl(220, 10%, 40%);
}
/* ...misc */
.CodeMirror-scrollbar-filler, .CodeMirror-gutter-filler {
  background-color: #ccc; /* The little square between H and V scrollbars */
}

/* Cursor */

.CodeMirror-cursor {
  border-left: 2px solid hsl(220, 100%, 66%) !important;
}
.CodeMirror-overwrite .CodeMirror-cursor {
  border-left: none !important;
  border-bottom: 1px solid #fff;
}

/* Popular addons */

/* addon: adit/machingbrackets.js & addon: edit/matchtags.js   */
.CodeMirror-matchingbracket, .CodeMirror-matchingtag {
  /* Ensure visibility against gray inline editor background */
  background-color: rgba(204, 217, 255,0.09);
  color: hsl(220, 14%, 71%) !important;
  border-bottom: 1px solid hsl(220, 100%, 66%);
}


/* Syntax Theme /---------------------------------------------------------------------------------- */


/* markdown */
.cm-header {color: #e06c75;}
.cm-quote {color: #5c6370;font-style: italic;}

.cm-negative {color: #e06c75;}
.cm-positive {color: #e06c75;}

.cm-strong {color: #d19a66;font-weight: bold;}
.cm-header .cm-strong {color: #d19a66;font-weight: bold;}

.cm-em {color: #c678dd;font-style: italic;}
.cm-header .cm-em {color: #c678dd;font-style: italic;}

/* xml, html, ... */
.cm-tag {color: #e06c75;}
.cm-attribute {color: #d19a66;}
.cm-link {color: #98c379;border-bottom: solid 1px #98c379;}

/* other ... (for example javascript) */
.cm-builtin {color: #e06c75;}
.cm-keyword {color: #c678dd;}
.cm-def {color: #e5c07b;} /* original:  #d19a66; */

.cm-atom {color: #d19a66;}
.cm-number {color: #d19a66;}
.cm-property {color: #61afef;} /* original: #abb2bf */
.cm-qualifier {color: #d19a66;}

.cm-variable {color: #e06c75;}
.cm-variable-2 {color: #abb2bf;}
.cm-variable-3 {color: #e5c07b;}

.cm-string {color: #98c379;}
.cm-string-2 {color: #98c379;}

.cm-punctuation {color: #abb2bf;}
.cm-operator {color: #abb2bf;}
.cm-meta {color: #abb2bf;}
.cm-bracket {color: #abb2bf;}
.cm-comment {color: #5c6370;font-style: italic;}

`
I referenced the above style sheet so you know I did try.

I will spend more time on it and look for the the editor's correct function name for the settings api. I am sure it can be done with the settings api correctly.

**Comment by radfordwill** [comment]
It's a hard one, may have bitten off more than I can chew right now. I can't de-register a script without errors and of course a new instance produces both. 

The api uses this
`cm.setOption(option: string, value: any)`

but produces errors no matter what function it is in or what I use for reference. No hook for the new editor that I can find. 

You can still load a codemirror themed css file with 
`.cm-s-default.CodeMirror { background: #0C1021; color: #F8F8F8; } etc...`


In any case I'm taking a break, Happy Thanksgiving!

**Comment by radfordwill** [comment]
```
function wp_enqueue_code_editor( $args ) {
	if ( is_user_logged_in() && 'false' === wp_get_current_user()->syntax_highlighting ) {
		return false;
	}

	$settings = array(
		'codemirror' => array(
			'indentUnit' => 4,
			'indentWithTabs' => true,
			'inputStyle' => 'contenteditable',
			'lineNumbers' => true,
			'lineWrapping' => true,
			'styleActiveLine' => true,
			'continueComments' => true,
		'theme' => 'midnight',
			'extraKeys' => array(
				'Ctrl-Space' => 'autocomplete',
				'Ctrl-/' => 'toggleComment',
				'Cmd-/' => 'toggleComment',
				'Alt-F' => 'findPersistent',
			),
............. if only...

```
[](https://developer.wordpress.org/reference/functions/wp_enqueue_code_editor/)


would wordpress add a hook for this function? nothing else for now.

**Comment by radfordwill** [comment]
```
// codemirror addon theme "one-dark"
wp_enqueue_style( 'dark-mode-cm-theme', plugin_dir_url( __FILE__ ) . 'one-dark.css' );
// wp_code_editor_settings is new as of 4.9...
function dark_mode_wp_editor_settings( $settings ) {
	$new_settings =
		array( 'codemirror' => array( 'theme' => 'one-dark' ) );
	$settings = array_merge( $settings, $new_settings );
	return $settings;
}
add_filter( 'wp_code_editor_settings', 'dark_mode_wp_editor_settings' );
```


[one-dark.zip](https://github.com/danieltj27/Dark-Mode/files/1502719/one-dark.zip)
I changed the background color to suit and font size to inherit if I remember right.

I just found this hook today after searching all through the wp codex and files for one. Should have looked closer but I wonder how old that page is?

The theme editor and widget html editor are styled correctly. 
Only negative thing is, the linting and brackets match highlighting is in the wordpress default theme I think. I am working on it tonight though. I don't think it is a settings problem, we aren't overriding any. 

It's a start,
enjoy :)

**Comment by radfordwill** [comment]
Bad news for me,

I don't see how it can be done other than overriding the codemirror default style sheet.


This should work at the least:

```
// codemirror addon theme "(default) dark-mode"
wp_enqueue_style( 'dark-mode', plugin_dir_url( __FILE__ ) . 'default.css' );
// wp_code_editor_settings is new as of 4.9...
function dark_mode_wp_editor_settings( $settings ) {
	$new_settings =
		array( 'codemirror' => array( 'theme' => 'default' ) );
	$settings = array_merge( $settings, $new_settings );
	return $settings;
}
add_filter( 'wp_code_editor_settings', 'dark_mode_wp_editor_settings' );

```

but it doesn't load whatever javascript or utilize the css that does linting, bracket matching etc. I looked for dependencies for "cm-s-default" in the default scripts but nothing stood out. Just setting codemirror to use a different style sheet stops it from using the custom linting etc. Catch-22, I can change the theme but linting stops. I can override the default css but how long will it last? Liberal use of !important got the job done but hate using it unless nothing else works.


The default theme is built in too far for me. It would take a lot of javascript to be added. I de-registered the codemirror script and it crashed. Same thing with code-editor scripts. So css it is for me. Maybe if codemirror theming was included in core it could be done easier. I did try de-registering and reloading the code editor scripts but no dice. 

`wp_enqueue_style( 'dark-mode', plugin_dir_url( __FILE__ ) . 'default.css' );`
[default.zip](https://github.com/danieltj27/Dark-Mode/files/1502837/default.zip)


Using the above theme. I started with the default theme and changed to mute colors. Any ideas?

**Comment by radfordwill** [comment]
The codemirror CSS classes can be overridden. I styled this one to dark colors.

[default.zip](https://github.com/danieltj27/Dark-Mode/files/1520069/default.zip)

Just load it with wp_enqueue_style().  

Someone will have to add support for themes in wp-includes\general-template.php

**Comment by danieltj27** [comment]
Sorry for the long absence, I was away.

Thanks for digging into this issue deeper and exploring ways to style it. Personally, I don't have a preference as to whether we style this or not. My opinion for not styling the text editor (TinyMCE) is that themes can do this and Dark Mode won't necessarily have any impact on the front-end anyway.

However, I do like the idea of making the code editor a darker theme, whether it's a pre-made one (license permitting) or custom made. I'd need to look into this further to see what the best approach is and we should try to use the current set of hooks and filters available to us for the best coverage for users. Perhaps it's worth seeing if we can easily just bundle a theme when Dark Mode is on to make sure we get this styled?

Could you submit any code changes as a PR please? That'll make it easier to review in one go and merge any changes that should go into the plugin. Thanks for the hard work so far!

**Comment by radfordwill** [comment]
Submitted PR for codemirror style sheet. I couldn't find a way to add it to your style sheets safely so I created a new one. Not sure if if you would combine them.

**Comment by danieltj27** [comment]
Addressed in PR #42. Awaiting changes.

**Comment by danieltj27** [comment]
Marking this as need changes because the CM CSS is now bundled but not complete yet. I only tested it with a small amount of CSS. Looks okay so far but needs more work to it. Will leave this issue open to continue tracking it.

**Comment by radfordwill** [comment]
Tested it and it looks good. Now that you added the styling I can add more styling if you like. I started out using Atom's color scheme. I think we should try to match it as close as possible as it's a great palate and easy to read on a dark background.

**Comment by danieltj27** [comment]
Yeah that’s fine - if you add new colours, make sure you add them as new colour variables under the second set of colours and use `codemirror` as a prefix so you can tell what they’re used for. If you want to submit anymore PRs please do by all means!

**Comment by radfordwill** [comment]
I styled the code editor to match atom's one dark theme. I have a question about scss though. I know scss treats dashes and underscores the same way but what about class names?

```
body .cm-variable-2 {
	color: #e06c75 !important;
}
```

converts to:
```
&-variable_2{
       color: $sunglo;
}

```

Seems like common sense but I'm a sass amateur. 

I also left the css file expanded, that was the way you wanted it submitted for a pr right? 

Not being a stickler, just making sure I have it right before I submit anything.

https://github.com/radfordwill/Dark-Mode

**Comment by danieltj27** [comment]
No worries, that's right. So this:

```
body {
  &.class {
    background: $red;
  }
}
```

Becomes:

```
body.class {
  background: #ff0000;
}
```

I'll have a look at the Sass you have and see what it's like. If you follow what is already in the Sass file as best you can it'll probably be fine anyway. In terms of having a 'theme' to work from like Atom you mentioned, that's totally cool, as long as we have all the colours used in Sass variables so they can be changed if need be.

**Comment by danieltj27** [comment]
I've had a quick glance over it and from the changes I can see, the only thing I'd change it the names of the colour variables. So you've added a variable like `$lavender`, I'd change that to `$editor-lavender` so we know where that colour is used as the code editor colours will likely only be used for the editor and nowhere else.

Leave all the accent colours as they are though, no need to update the prefix for those ones. Nice 👍

**Comment by danieltj27** [comment]
Adding the `Important` label to this issue because I want to have this issue closed and completed and then we can release version 1.5.

**Comment by radfordwill** [comment]
https://github.com/danieltj27/Dark-Mode/pull/52

created a pull request. 3 colors added with naming convention you asked for in darkmode.scss.

**Comment by radfordwill** [comment]
pulled new revision and added new style changes. not sure why I started with the old one.  holidays i guess.

**Comment by danieltj27** [comment]
When you first forked the repository it was prior to quite a few changes that we'd made recently so it fell behind. I've merged the PR now into the code base. Thanks for helping!

**Comment by radfordwill** [comment]
no problem, thank you for the dark mode features. I enjoy the benefits every time I use wordpress admin now.
