### ISSUE TITLE
fix CSS for missing background color in WP Settings

### ISSUE THREAD

**Issue by Presskopp** [danieltj27/Dark-Mode#45]
```
#wpwrap {
    background-color: #23282d;
}
```

I think we need to add this to get the whole background colored, I first said this in #28, but color was wrong there. Some don't like to add CSS rules by ID, but I can't tell a better solution.

**Comment by Presskopp** [comment]
![image](https://user-images.githubusercontent.com/18373563/33623219-90ad6daa-d9f0-11e7-85cf-02e87b668942.png)

**Comment by Presskopp** [comment]
with fix

![image](https://user-images.githubusercontent.com/18373563/33623364-03a5d478-d9f1-11e7-8825-8c20e2f4579c.png)

**Comment by danieltj27** [comment]
That's strange - I can't replicate this issue. What's your screen size?

**Comment by Presskopp** [comment]
found the reason, WP Admin Color Schemes Plugin - but this should still not be, who's to blame?

**Comment by danieltj27** [comment]
Hmm, well there's no harm in forcing the colour our end. Check commit 03cf82d fixes this. I added in some extra rules to address this. Hopefully we can tick this off.

**Comment by Presskopp** [comment]
Looks good to me, worksforme
