### ISSUE TITLE
Disabled input fields don't look inaccessible

### ISSUE THREAD

**Issue by danieltj27** [danieltj27/Dark-Mode#48]
I've just noticed that disable fields in the dashboard UI look like normal (non-disabled) fields and it's not visually clear that you cannot select and edit the contents of them.

An example of this is the username field on the profile page (/profile.php). It looks like you can click on it to select and edit the text but that field is always disabled.

**Comment by Presskopp** [comment]
My 2c to get this forward:

```
input[type="text"]:disabled {
    background-color: #32373c;
}
```

**Comment by danieltj27** [comment]
If you can change that to use a variable, that's `$base-grey` isn't it - then put that in a PR if you have time before I do then that'd be awesome. If not I can sort it later. 👍

**Comment by Presskopp** [comment]
No, it's `$dark-grey` - PR is here: https://github.com/danieltj27/Dark-Mode/pull/51
