### ISSUE TITLE
Update the standard button hover state styles

### ISSUE THREAD

**Issue by danieltj27** [danieltj27/Dark-Mode#49]
I've battled with this for a while and can't seem to get the hover state for secondary buttons quite right. Currently, the default state is grey, which is fine, but on hover it changes (the background colour) to dark grey / black and is hard to differentiate from the background of the dashboard. This needs changing to something else so it's more clear that you are hovering over the button.

**Comment by Presskopp** [comment]
Looks like we have to check different cases, not sure where you've spotted this originally. I found the following places that needs improvement:

1: Permalink tags:
![1 permalinks](https://user-images.githubusercontent.com/18373563/33778238-2bb5bab0-dc48-11e7-8968-f98647da7493.png)

Patch idea:
`.button-secondary.active {
    background-color: #bbc8d4 !important;
}`

![2 permalinks patched](https://user-images.githubusercontent.com/18373563/33778261-3f670f0a-dc48-11e7-81a5-9d0062a1887a.png)

2: Delete Theme:
![3 theme delete](https://user-images.githubusercontent.com/18373563/33778321-761cefe2-dc48-11e7-9d7d-ed020735fd53.png)

Patch idea:
`a.button.delete-theme {
    background-color: #DC3232!important;
}`

![4 theme delete patched](https://user-images.githubusercontent.com/18373563/33778358-941ba772-dc48-11e7-98a2-9b1f44944bf0.png)

3: Generate new password on hover, not sure if it needs a patch
![5 new password](https://user-images.githubusercontent.com/18373563/33778389-b37b1f1c-dc48-11e7-9f48-45556d3415dd.png)

Seems impossible to patch without `!important` ..

**Comment by danieltj27** [comment]
I noticed that all secondary buttons in general didn't have an overly great hover style. I think we'll need to just go through each of the highlighted buttons and sort them out as we see them. Lots of UI buttons in Core have all sorts of styling added to them.

**Comment by danieltj27** [comment]
Fixed this in commit 00b3868 (_I think_).
