### ISSUE TITLE
Media attachment popup not styled

### ISSUE THREAD

**Issue by danieltj27** [danieltj27/Dark-Mode#58]
When looking at the media library in grid mode, clicking on media will show a popup modal. This popup is completely unstyled and needs some attention. It looks as if none of the Dark Mode styling is actually affecting the UI of this which is strange.

**Comment by Presskopp** [comment]
trying `.media-modal.wp-core-ui *`

**Comment by Presskopp** [comment]
next iteration to try:

`.media-modal.wp-core-ui * {
    background-color: #23282D;
}
.actions, .media-frame-title * {
    color: #bbc8d4;
}`

Also we need a solution for the grid/list view icons, one stays invisible clicking the other

**Comment by danieltj27** [comment]
On the right lines, needed a bit more attention though as it's placed outside the normal dashboard container tags. I've fixed this in commit b629a8c.
