### ISSUE TITLE
Plugin update notice not styled

### ISSUE THREAD

**Issue by danieltj27** [danieltj27/Dark-Mode#59]
I'm not sure about this if you update a plugin from the plugin list (via a shiny update), however if you go to the updates page and update a plugin from the table (`wp-admin/update-core.php`) then once a plugin has been updated, the notice that appears for a successful update doesn't have the correct background on it.

CSS classes need adding to fix this, potentially only `.updated`.

```
.update-php div.error, .update-php div.updated
```

**Comment by Presskopp** [comment]
confirmed, bug as well as solution, style class `.updated`. should do it

**Comment by Presskopp** [comment]
In darkmode.scss there's already:

`.notice,
div.error,
div.updated,
div.update-nag {
background-color: $dark-grey;
}`

I ask myself: Will it be enough to cut the **div.** from div.updated ? Else class _.updated_ needed to be added to those.

**Comment by danieltj27** [comment]
Thanks for the tip, that did the trick. RE: 6f5c427.
