### ISSUE TITLE
Auto Dark Mode doesn't work with end time

### ISSUE THREAD

**Issue by danieltj27** [danieltj27/Dark-Mode#60]
This has been brought up by @Presskopp a few times and I couldn't replicate it properly until now. It seems as if the automatic Dark Mode isn't working correctly due to the end time not being respected. After testing the various time examples, it appears that the start and end time are conflicting.

For example:

- Start time is `19:35 pm` and end time is `06:30 am` and the current time is `21:10 pm`, then it should work fine, without any issues.

- Start time is `15:55 pm` and the end time is `03:25 am` and the current time is `01:20 am` then it won't work properly.

To fix this, I think we need to check if the end time is smaller than the start time and if it is, we need to add `+1 days` to the end time so it's technically the next day. This was taken out of a previous commit but it seems like it's necessary to add back in again. Will be worth testing out a proposed fixed soon to see.

**Comment by Presskopp** [comment]
I (still) think differently. I don't need the +1 day to have a working auto mode. My code may be bloated but it works (I use Dark Mode including it since it exists privately!). I'll share this here including comments on your examples + new ones turning (correctly) to the appropriate state:

`				// example 1: start time = 19:35, end time = 06:30, current time = 21:10
				// example 2: start time = 15:55, end time = 03:25, current time = 01:20
				// example 3: start time = 15:55, end time = 03:25, current time = 05:20
									 
				if ( ( $user_dm_start > $user_dm_end ) && ( ( $current_time >= $user_dm_start ) || ($current_time <= $user_dm_end ) ) ) {
					
					// example 1: if (true)&&(true||false) => true
					// example 2: if (true)&&(false||true) => true
					// example 3: if (true)&&(false||false) => false
					
					// Dark Mode is set automatically and on right now
					return true;
				} else {
					
					/**
					* Check if start time is less (or equals) end time
					* and if the current time is within the time frame
					* so it can be enabled.
					*/
					
					
					// example 4: start time = 06:55, end time = 18:25, current time = 04:20
					// example 5: start time = 06:55, end time = 18:25, current time = 17:20
					
					if ( ( $user_dm_start <= $user_dm_end ) && ( ( $current_time >= $user_dm_start ) && ($current_time <= $user_dm_end ) ) ) {

						// example 4: if true && (false && true) => false
						// example 5: if true && (true && true) => true
					
						// Dark Mode is set automatically and on right now
						return true;
						
					} else {
					
						return false; // not in timeframe
					
					}
					
				}
				
			} else {
				// It is always on
				return true;
			}
		}
		// It is not enabled
		else {
			return false;
		}`

**Comment by Presskopp** [comment]
Please check latest version here:
https://github.com/Presskopp/Dark-Mode/commit/78318309c123eb275f9fbab5a5e6be2f361e2156

**Comment by danieltj27** [comment]
I'll merge what you have into the master branch and double check it's working. I'm keen to get this sorted so we can focus on the CSS as it needs a lot of attention.

**Comment by danieltj27** [comment]
Based on @Presskopp commit above, in commit d9e5312 this should be fixed for good now (I hope). I manually set the time to various different test cases and in each scenario it worked as intended. I think what was causing issues was this logic (pseudocode for example):

```
IS current_time BIGGER THAN start_time OR current_time SMALLER THAN end_time
```

Whereas it should have been:

**Comment by Presskopp** [comment]
Just happened to me:

 $auto_start: 2018-01-12 17:40:00
 $auto_end: 2018-01-13 08:00:00
$current_time: 2018-01-12 01:43:57

so ( $current_time <= $auto_end ) is true, while
( $current_time >= $auto_start ) is **false**,

so if ( $current_time >= $auto_start && $current_time <= $auto_end ) gets false and Dark Mode is **not** enabled where it should be. Still some bug, or is it in my head?

**Comment by danieltj27** [comment]
That's correct (the functioning).

So this is in two parts;
- It checks that `current_time is BIGGER OR EQUAL to start`.
And
- It checks that `current_time is SMALLER OR EQUAL to end`.

So essentially is testing that it's after 8pm but before 6am for example.

- `2am (next day, current) is BIGGER OR EQUAL to 8pm (previous day, start)`
And
- `2am (next day, current) is SMALLER OR EQUAL to 8pm (previous day, start)`

> $auto_start: 2018-01-12 17:40:00
> $auto_end: 2018-01-13 08:00:00
> $current_time: 2018-01-12 01:43:57

So what you've described is fine and is working as intended as the time is 1am on the 12th and Dark Mode comes on at 17:40 pm on the 12th (same day). It then should turn off after 8am (13th).

So the above example Dark Mode **should not** be enabled yet.
