### ISSUE TITLE
Suggestion for default theme bar and menu colors

### ISSUE THREAD

**Issue by rubengc** [danieltj27/Dark-Mode#62]
I just test the plugin and it is amazing!

As suggestion for default theme I recommend to change color of admin bar and menu to WordPress primary color (#0073aa)

Just test it:
```
#adminmenu, #wpadminbar {
    background-color: #0073aa;
}
```

**Comment by Presskopp** [comment]
Hi, may I ask how this would play well in combination with admin color schemes ?

**Comment by rubengc** [comment]
This suggestion is just for default color scheme instead of keep it dark too

**Comment by rubengc** [comment]
The idea is to switch from this:
![old-default-scheme](https://user-images.githubusercontent.com/5462480/34454772-ba6312d6-ed72-11e7-82d4-ff9378d24b08.PNG)
To this:
![new-default-scheme](https://user-images.githubusercontent.com/5462480/34454773-ba7d58e4-ed72-11e7-8f7b-152829f63241.PNG)

**Comment by danieltj27** [comment]
Hi @rubengc thanks for the suggestion. As @Presskopp has pointed out, this falls into the remit of admin colour schemes which Dark Mode doesn't deal with as it's a separate area of concern.
