### ISSUE TITLE
Doesn't activate/work on some shared hosts

### ISSUE THREAD

**Issue by nekohayo** [danieltj27/Dark-Mode#66]
First and foremost: THANK YOU for working on this in the hope of getting it integrated as a core wordpress feature. I've been waiting for this *forever* and all plugins that attempted to do this have been broken for years.

Now that this is said: I have tried to simply install it from within my Wordpress 4.9.1's native plugins manager UI, on my website that runs on a shared hosting service (Hostgator)*, but it fails to activate, giving this error:

> Plugin could not be activated because it triggered a fatal error.
> Fatal error: Can't use function return value in write context in /path_to_the_blog/wp-content/plugins/dark-mode/dark-mode.php on line 310

*: probably with ye olde PHP 5.4 because that's what runs on many many shared hosts because they usually are based on RHEL/Centos.

Some hint as to the potential misuse of "empty()": https://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context

**Comment by danieltj27** [comment]
Thanks for your kind words! I'll look into this as part of the next release (1.6). If you can check v1.6 (when it's out, some point soon) and see if this works that'd be great. 👍

**Comment by danieltj27** [comment]
This should hopefully now be fixed in commit d9e5312. If you have a chance to test this before 1.6 is in the plugin directory that'd be great, if not then no worries. Thanks again for the report! 👍

**Comment by nekohayo** [comment]
Applied the 1.6 update and it worked. Beautiful. Thanks for the quick turnaround!
