### ISSUE TITLE
Usability: clarify what types of hours input are accepted in the UI

### ISSUE THREAD

**Issue by nekohayo** [danieltj27/Dark-Mode#68]
As most users never RTFM, the hours of automatic operation in the preferences for darkmode (in the user profile settings) should indicate what kind of input is accepted... ex: 13, 13:45, 13h45, 1345, 13h,  1PM, "a quarter to two after lunch" (just kidding) etc. Maybe with some placeholder text, or some "(?)" tooltip hover thingy, or (worst case) a label on the side.

**Comment by danieltj27** [comment]
Ah, I take it that you're not seeing the same input text box as I'm seeing.

It should be `00:00` in 24 hour formatting. Thanks for letting me know about this.

What browser are you using?

**Comment by nekohayo** [comment]
This is what I see with Firefox 56:

![dark-mode-hours](https://user-images.githubusercontent.com/479401/34695265-2f57e2f2-f498-11e7-88f3-4fa42d8c3466.png)

**Comment by danieltj27** [comment]
Interesting, that's completely different to what I'm seeing in Chrome.

I'll need to look into it further but Firefox obviously doesn't like `input[type="time"]`. Thanks!

**Comment by Presskopp** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=888320
https://caniuse.com/#feat=input-datetime

**Comment by danieltj27** [comment]
[Placeholders for inputs](https://caniuse.com/#feat=input-placeholder) have good browser support. I think a good solution is to just add a placeholder in so people know, maybe need some input verification for the format though. Not much else we can do in this scenario, and adding any jQuery support to alter the input is way to overkill for something this small.

**Comment by danieltj27** [comment]
I think the best we can do for now is to add placeholder text to the inputs which I've done and committed in 1.8. Browser support should be good enough for this to be a sensible solution.

Committed in 76cb307.
