### ISSUE TITLE
Enable Dark Mode globally for all users

### ISSUE THREAD

**Issue by danieltj27** [danieltj27/Dark-Mode#69]
Someone on the WordPress forums has suggested that there be a method to turn on Dark Mode globally without the/a user explicitly turning it on. I like the idea.

Two options for implementation:
- Set a flag such as `define( turn dark mode on globally )`
- Add an option in (perhaps) General settings to turn on globally

Any thoughts?

**Comment by Presskopp** [comment]
flag please. I thought about having it on wp-admin/users.php, but, not, let's define it.

**Comment by danieltj27** [comment]
Sure 👍 

Personally, I see the user flow as being:

- Activate plugin and off for everyone.
- Users can choose to enable it.
- Add a flag to turn on for everyone, but if any specifically turns it off (ie. turns it on and then off again so they have the option saved as off) then it stays off.

I think that's the most effective and less intrusive way of doing it.

**Comment by danieltj27** [comment]
Will add this in milestone 2.0 as a filter to enable for users who don't have a preference set yet.

**Comment by danieltj27** [comment]
Pushing this back into the 2.1 release. Should be available via flag (as a filter).

The logic we'll need here is to check if a Dark Mode preference is set in the database, if it's not, through a filter (perhaps `no_dark_mode_preference`) with a boolean value of false that when true will turn it on.

If a preference is set, either turn it on (if on) or off (if off).

**Comment by danieltj27** [comment]
This is now available in version 2.0.

You can use the `is_using_dark_mode` and `not_using_dark_mode` filters to always return true forcing Dark Mode to always be on. Adding some extra logic will allow you to check if a preference is set first before returning a value.

**Comment by danieltj27** [comment]
Please refer to [the documentation](https://github.com/danieltj27/Dark-Mode/wiki/Filter:-not_using_dark_mode) for using the filter hook to force Dark Mode on.
