### ISSUE TITLE
The Plugin “Dark Mode” has been removed from wordpress.org

### ISSUE THREAD

**Issue by kalich5** [danieltj27/Dark-Mode#70]
This plugin was closed on January 12, 2018 and is no longer available for download. 👎

**Comment by danieltj27** [comment]
This should be fixed in commit ade5a66. Version 1.7 in the plugin directory should address this issue.

**Comment by danieltj27** [comment]
Dark Mode is now back in the plugin directory. Sorry for any inconvenience!
