### ISSUE TITLE
Couldn't find Dark Mode settings

### ISSUE THREAD

**Issue by mwaterous** [danieltj27/Dark-Mode#72]
I stumbled across your plugin on the WordPress repository and thought I'd give it a try! I prefer a dark color scheme for Chrome Inspector tools and thought maybe this might be the answer to that in WordPress.

Right off the line I got lost trying to find out how to turn Dark Mode on. I know there's an installation tab on the repository and I should've read it, but I think I'm like a lot of users in that I activate plugins and expect something to hit me in the face.

You might want to add an "Enable Dark Mode" to the plugin action links that sends you to the user profile page. This could eliminate some potential complaints from people as dumb as myself.

**Comment by danieltj27** [comment]
Hi, thanks for your suggestion. Dark Mode is enabled on a user-by-user basis so you'll need to personally turn it on to see it. There was some discussion about having it on by default for everyone unless explicitly turned off by a user in Issue #69.

Nonetheless, thanks for the feedback. I think the installation instructions could be clearer.

**Comment by mwaterous** [comment]
I think you're misunderstanding me. I'm not suggesting that anything be turned on by default, and your instructions (on the repository) are clear.

However, if a user downloads the plugin directly from their dashboard and activates it, it is not clear where the on/off switch is located (on your user profile page). Having a link below the plugin might be a benefit here, such as this:

<img width="573" alt="plugins_ _wordpress_ _wordpress" src="https://user-images.githubusercontent.com/6832116/35394268-90d36c68-01a4-11e8-84ce-b5423b4a21a3.png">

Hope that helps!

**Comment by danieltj27** [comment]
Oh I see, sorry. That makes sense. A link to the user profile would be handy here. Okay that's something we could look into implementing.

**Comment by danieltj27** [comment]
I've removed the tab from the toolbar and moved it into the plugin table. Thanks for the suggestion.

Fixed in commit 76cb307.
