### ISSUE TITLE
Spinner looks ugly when dark mode active

### ISSUE THREAD

**Issue by Presskopp** [danieltj27/Dark-Mode#75]
Well, not a big issue, but still an issue. When waiting for an action and the spinner.gif comes up, while dark mode is active, you'll see an ugly white border around it. Should we exchange this via CSS? Is this even possible?

![spinner](https://user-images.githubusercontent.com/18373563/35852982-a0d5d380-0b2c-11e8-8bee-efaf9418c3f4.gif)

**Comment by Presskopp** [comment]
![image](https://user-images.githubusercontent.com/18373563/35853072-dcd31ed8-0b2c-11e8-837c-a0b4a6905448.png)

**Comment by danieltj27** [comment]
All spinners in the default UI should have a `.spinner` class on them, so it's possible that that could maybe add a small 1 or 2 pixel border to the image to smooth it out a bit. Swapping the image out may be possible, but loading another asset just for decorative purposes seems pointless. The border solution might work though.

**Comment by Presskopp** [comment]
I had some time to play and after failing to apply a border like you proposed, I had another idea, that looks promising:

```
.spinner {
    filter: invert(100%);
}
```

[Browser support](https://caniuse.com/#search=invert)

**Comment by danieltj27** [comment]
Hmm, I'm not sure because it flaky browser support for Edge and nothing for IE which WordPress still has support for IE versions. Not sure about this one then. Perhaps the spinner just needs updating in Core?

**Comment by Presskopp** [comment]
Also not sure, but I think it's a small price.

**Comment by danieltj27** [comment]
Added background and border to spinner element.

Fixed in commit 76cb307.
