### ISSUE TITLE
 adding the darkmode body class

### ISSUE THREAD

**Issue by unseizissable** [danieltj27/Dark-Mode#81]
it might be interesting to add a body class so that I can adjust my plugins to this super mod that I just discovered
good job i love

**Comment by danieltj27** [comment]
Thanks for the kind words! You can use the action hook `doing_dark_mode` to enqueue your plugins stylesheet whilst Dark Mode has been activated. That will let you include your CSS on any of your plugin pages that need CSS changes. 👍
