### ISSUE TITLE
Toggle Dark Mode on the User submenu

### ISSUE THREAD

**Issue by yuanworks** [danieltj27/Dark-Mode#91]
I noticed that while using this plugin, sometimes I wish to toggle it quickly, for example when a plugin is using their own CSS which messes up the dark mode.

The right-hand side user sub menu is relatively empty and it could be included there:

![image](https://user-images.githubusercontent.com/3508123/40092644-e1e5bebe-58f0-11e8-9200-2c25e7cd5f3d.png)

I was checking the WP hooks and filters and I'm not sure whether or not that menu can be overridden (WP docs are not exactly easy to navigate). If someone can point me on the right direction, I can give it a go and add this feature to the plugin.

PD: I really love the idea of this plugin, I wake up around 4am when the sun is not yet out and this makes a big difference. Hope I can contribute to make it a reality in WP Core!

**Comment by danieltj27** [comment]
Hi @yuanworks thanks for the kinds words!

Right now the project is in a sort of feature-freeze phase to prepare it for inclusion in core (still need to do a merge proposal first though). It wouldn't be a bad idea to add this as a new plugin, similar to the [Automatic Dark Mode plugin](https://gist.github.com/danieltj27/8624d57c5e0f30465f963bc7838bbb7f) (which was formerly part of the Dark Mode core plugin).

This is just a super quick example:

```
add_action( 'admin_bar_menu', 'dark_mode_toolbar', 10, 0 );

function dark_mode_toolbar( $wp_admin_bar ) {
	$args = array(
		'id' => 'toggle_dark_mode',
                 'parent' => 'my-account',
		'title' => 'Toggle Dark Mode',
		'href' => 'http://example.com/wp-admin/'
	);
	$wp_admin_bar->add_node( $args );
}
```

The[ documentation for the toolbar](https://codex.wordpress.org/Class_Reference/WP_Admin_Bar/add_node) is, like you said tricky to navigate but you can add menu items (or nodes) using a simple hook process like above. It should be relatively easy to do this though and when you click on the link provided, it toggles it either on or off.

So, yeah, I don't think adding this to the core plugin is the best approach, at least for now. But can be made into an additional plugin if you'd like and feedback that I'll definitely take on board. :)
