### ISSUE TITLE
Different color for primary button styling

### ISSUE THREAD

**Issue by yuanworks** [danieltj27/Dark-Mode#94]
Dark mode `.button-primary` style (see "intended" on the screenshot) is not been displayed because it's overridden by `.button` ("current version" on screenshot), leading to secondary and primary buttons appearing to be the same on dark mode:

![image](https://user-images.githubusercontent.com/3508123/40153658-5db0b59a-59bd-11e8-8901-77a005c4498f.png)

**Comment by danieltj27** [comment]
Thanks for reporting this. I'll look into it.

**Comment by danieltj27** [comment]
Fixed in PR #95.
