### ISSUE TITLE
WP-pointer-content (pop-ups) CSS styling

### ISSUE THREAD

**Issue by yuanworks** [danieltj27/Dark-Mode#96]
Add dark-mode for the sporadically-used `wp-pointer-content` class:

![image](https://user-images.githubusercontent.com/3508123/40289843-57ccf840-5ced-11e8-9ecd-199c64f56863.png)

**Comment by danieltj27** [comment]
Changing to the Core Release milestone.

**Comment by danieltj27** [comment]
I didn't think when I added the labels I'd fix this so quickly, but I did 😃 

Fixed in commit 597f82d.
